### ISSUE TITLE
mongodb<4.0 amazonlinux install error

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_mongodb#1]
change repo from amozon to redhat

**Comment by zengxc-1996** [comment]
## AWS linux2 3.x tested:
![image](https://user-images.githubusercontent.com/63622990/116506854-b196ce80-a8f0-11eb-9bb6-3e8898e33adf.png)
![image](https://user-images.githubusercontent.com/63622990/116507418-d0499500-a8f1-11eb-9bb8-49df3a31fe78.png)
![image](https://user-images.githubusercontent.com/63622990/116507604-21598900-a8f2-11eb-8997-f8917d49a51c.png)
![image](https://user-images.githubusercontent.com/63622990/116508681-71394f80-a8f4-11eb-9bd3-a206bbc58ce5.png)

## adminmongo 3.x 4.x:
![image](https://user-images.githubusercontent.com/63622990/116508892-e60c8980-a8f4-11eb-800f-561c0588a84c.png)
![image](https://user-images.githubusercontent.com/63622990/116509155-67641c00-a8f5-11eb-9a0e-cf4591542620.png)

## Among them, 3.3 3.5 3.7 is unstate version;

## AWS linux2 4.x tested:
![image](https://user-images.githubusercontent.com/63622990/116508940-fde40d80-a8f4-11eb-8627-2e8d6ea00f3a.png)
![image](https://user-images.githubusercontent.com/63622990/116508993-13593780-a8f5-11eb-9521-87dbdec3639b.png)
![image](https://user-images.githubusercontent.com/63622990/116509248-8fec1600-a8f5-11eb-870f-c1f4c5ec1599.png)
