### ISSUE TITLE
Cloud Native Database for MongoDB 3.4 (Ubuntu 16/18/20)

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_mongodb#2]

**Comment by zengxc-1996** [comment]
support version:
![image](https://user-images.githubusercontent.com/63622990/116499702-60caaa00-a8df-11eb-8050-f0ee2c344117.png)

**Comment by zengxc-1996** [comment]
AWS ubuntu 16.04 tested mongodb 3.4 is ok.


![image](https://user-images.githubusercontent.com/63622990/116507266-8365be80-a8f1-11eb-92ec-a67aad6c432e.png)


not support ubuntu 18.04 and 20.04.

**Comment by qiaofeng1227** [comment]
Done
