### ISSUE TITLE
  azure /aws    Ubuntu20.04 无法安装mongodb 4.4

### ISSUE THREAD

**Issue by tqf6** [Websoft9/role_mongodb#3]
## Language

- [ ] Chinese
- [ ] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: 
* Description: 
* Screenshot

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by qiaofeng1227** [comment]
can't reproduce
