### ISSUE TITLE
collection object is not callable pymongo

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/role_mongodb#6]
TASK [role_mongodb : Setting MongoDB Administrator User] ***********************
An exception occurred during task execution. To see the full traceback, use -vvv                                                                                                                                                             . The error was: TypeError: 'Collection' object is not callable. If you meant to                                                                                                                                                              call the 'add_user' method on a 'Database' object it is failing because no such                                                                                                                                                              method exists.
[WARNING]: Module did not set no_log for update_password
fatal: [104.43.202.231]: FAILED! => {"changed": false, "msg": "Unable to add or                                                                                                                                                              update user: 'Collection' object is not callable. If you meant to call the 'add_                                                                                                                                                             user' method on a 'Database' object it is failing because no such method exists.
  
![SH7OU{Q{4(Z6X$I~FF5O E0](https://user-images.githubusercontent.com/54173243/155042923-b4dd4efe-08f2-4e91-98af-121c4c544e5e.png)

**Comment by zengxc-1996** [comment]
![image](https://user-images.githubusercontent.com/63622990/155935490-21d57ac7-a12a-415e-b842-7789f6fc9b93.png)

Please change this line:  
docker-compose.yml 
${VOLUMES_PATH_PREFIX}/usr/share/zabbix/modules:/usr/share/zabbix/modules:ro

**Comment by zengxc-1996** [comment]
docker-compose v2 和 docker-compose v1  语法存在部分差异，基本上上下兼容。

**Comment by zengxc-1996** [comment]
This error is caused by an incompatibility with the newest version of pymongo that was recently released. 
you could simply exec into it and run python3 -m pip install pymongo<4 to install a compatible version.

**Comment by qiaofeng1227** [comment]
需要测试azure ubuntu20.04 ansible-ruby (mongodb选4.4和5) amazonlinux2  ansible-ruby (mongodb选4.4和5)

**Comment by qiaofeng1227** [comment]
This error is caused by an incompatibility with the newest version of pymongo that was recently released.
you could simply exec into it and run python3 -m pip install pymongo<4 to install a compatible version.
```
---
#1 pre-installation
- name: Install pymongo for Ansible MongoDB module
  pip:
    name: pymongo<4

```

**Comment by chendelin1982** [comment]
1. pip2 pip3 install pymongo manual
2. 安装和使用均需要指定python版本

**Comment by qiaofeng1227** [comment]
```
[root@websoft9-mediawiki-test-CentOS7 websoft9]# python2 -m pip install pymongo
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pymongo
  Downloading pymongo-3.12.3-cp27-cp27mu-manylinux_2_5_x86_64.manylinux1_x86_64.whl (504 kB)
     |████████████████████████████████| 504 kB 2.2 MB/s 
Installing collected packages: pymongo
Successfully installed pymongo-3.12.3
[root@websoft9-mediawiki-test-CentOS7 websoft9]# python3 -m pip install pymongo
Collecting pymongo
  Downloading pymongo-4.0.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (451 kB)
     |████████████████████████████████| 451 kB 5.1 MB/s            
Installing collected packages: pymongo
Successfully installed pymongo-4.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@websoft9-mediawiki-test-CentOS7 websoft9]# 
```

**Comment by qiaofeng1227** [comment]
```
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
python2 get-pip.py
```

**Comment by chendelin1982** [comment]
use docker replace it
