### ISSUE TITLE
adminMongo: 【Config error: MongoError: Authentication failed.】

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/role_mongodb#7]
platform: AWS
os: Ubuntu 20.0
version: MongoDB 5.0 
  
![P_ ZO1Q$%TA`~`_79179`MC](https://user-images.githubusercontent.com/54173243/162384679-0a0ea23c-01cb-4832-a773-ad09d206f3e1.png)

**Comment by qiaofeng1227** [comment]
not use mongodb
